config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  get '/cart', to: "carts#show"
  delete '/carts', to: "carts#destroy"
  post '/cart/add_item', to: "carts#add_item"
  post '/cart/subtract_item', to: "carts#subtract_item"

  resources :users, only:[:new, :create, :show, :edit, :update] do
    resources :orders, only: [:create, :show, :index]
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:create, :show, :update]

  get '/:category',  to: 'categories#show', param: :slug, as: "category"

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
    get "/dashboard", to: "users#show"
    delete "/dashboard", to: "users#destroy"
    post "/dashboard", to: "users#update"
    get '/analytics-dashboard', to: "analytics#show"
    post '/analytics-dashboard', to: "analytics#update"
    patch '/items', to: "items#retire"
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/cart.rb
class Cart

  attr_reader :contents

  def initialize(contents)
    @contents = contents || Hash.new(0)
  end

  def total_count
    contents.values.sum
  end



  def add_item(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def subtract_item(id)
    contents[id.to_s] -= 1
    contents.delete(id) if contents[id] == 0
  end

  def count_of(id)
    contents[id.to_s].to_i
  end



  def subtotal(id)
    item = Item.find(id)
    item.price * count_of(id)
  end

  def total_price
    result = 0.0
    contents.each do |id, quantity|
       result += Item.find(id).price * quantity
     end
     result
  end

  def remove_item(id)
    contents.delete(id.to_s)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper


  def create
    item = Item.find(params[:item_id])

    @cart.add_item(item.id)
    session[:cart] = @cart.contents

    flash[:notice] = "You now have #{pluralize(session[:cart][item.id.to_s], item.title)} in your cart!"

    redirect_to items_path
  end

  def show
    @items = Item.where(id: @cart.contents.keys)
  end

  def destroy
    @item = Item.find(params[:item_id])
    link = "<a href=\"#{url_for(@item)}\">#{@item.title}</a>"
    flash[:success] = "Successfully removed #{link} from your cart!"
    @cart.remove_item(params[:item_id])
    redirect_to cart_path
  end

  def subtract_item
    @cart.subtract_item(params[:item_id])
    item = Item.find(params[:item_id])

    flash[:success] = "Successfully removed from cart!"

    redirect_to "/cart"
  end

  def add_item
    @cart.add_item(params[:item_id])

    flash[:success] = "Successfully added from cart!"
    redirect_to "/cart"
  end
end

app/views/carts/show.html.erb
  <% if @cart.total_count != 0 %>
  <div class="carts-show">
    <% @items.each do |item| %>
    <div class="items">
    <% if item.image.nil? %>
    No image exists
    <% else %>
    <img src="<%= asset_path(item.image) %>"/>
    <% end %>
      Item: <%= item.title %><br/>
      Description: <%= item.description %><br/>
      Price: <%= number_to_currency(item.price) %><br/>
      <div class="quantity">
      Quantity: <%= @cart.count_of(item.id) %>
      <%= link_to "+", cart_add_item_path(item_id: item.id), method: :post %>
      <%= link_to "-", cart_subtract_item_path(item_id: item.id), method: :post %><br/><br/>
      </div>
      Item Subtotal: <%= number_to_currency(@cart.subtotal(item.id)) %>
    <%= link_to 'Remove', carts_path(item_id: item.id), method: :delete %>
    </div>
    <% end %>
  </div>
<h1>Total Price: <%= number_to_currency(@cart.total_price) %> </h1><br/><br/>
  <% else %>
    <h1>Your Cart is Empty!</h1>
  <% end %>
  <div class="checkout-button">
  <% unless current_user %>
    <%= link_to "Login or Create Account to Checkout", login_path %>
  <%else  %>
    <%= link_to "Checkout", user_orders_path(current_user), method: :post %>
  </div>
  <% end  %>