config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  get '/cart', to: "carts#show"
  delete '/carts', to: "carts#destroy"
  post '/cart/add_item', to: "carts#add_item"
  post '/cart/subtract_item', to: "carts#subtract_item"

  resources :users, only:[:new, :create, :show, :edit, :update] do
    resources :orders, only: [:create, :show, :index]
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:create, :show, :update]

  get '/:category',  to: 'categories#show', param: :slug, as: "category"

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
    get "/dashboard", to: "users#show"
    delete "/dashboard", to: "users#destroy"
    post "/dashboard", to: "users#update"
    get '/analytics-dashboard', to: "analytics#show"
    post '/analytics-dashboard', to: "analytics#update"
    patch '/items', to: "items#retire"
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :title, :description, :price, :category_id, :retire_count
  validates_uniqueness_of :title
  validates :price, numericality: {greater_than: 0}

  belongs_to :category

  has_many :item_orders, dependent: :destroy
  has_many :orders, through: :item_orders

  enum status: ["Active", "Inactive"]

    def retired_count
      self.increment! :retire_count
    end

    def self.order_by_retire_count
      where("retire_count > '0'").order(:retire_count)
    end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "You created the #{@item.title}!"
      redirect_to admin_items_path
    else
        render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    if @item.save
      flash[:success] = "#{@item.title} updated!"
      redirect_to admin_items_path
    else
      render :edit
    end
  end

  def retire
    item = Item.find(params[:item_id])
    if params[:update_status] == "Inactive"
      item.update(status: 0)
      redirect_to admin_items_path
    elsif params[:update_status] == "Active"
      item.retired_count
      item.update(status: 1)
      redirect_to admin_items_path
    else
      flash[:error] = "The Item could not be updated"
      redirect_to admin_items_path
    end

  end

  private

  def item_params
    params.require(:item).permit(:title, :description, :price, :image, :category_id, :status)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    @categories = Category.all
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/views/items/index.html.erb
<div class="categories-show">
  <% @items.each do |item| %>
  <div class="items">
    <%=link_to item.title, item_path(item) %>
    <p>Description: <%= item.description %></p>
    <p>Price: <%= number_to_currency(item.price) %></p>
    <div class="item_image">
      <% if item.image.nil? %>
      <p>No image available</p>
      <% else %>
      <img src="<%= asset_path(item.image)%>"/>
      <% end %>
      <p><%= item.category.title.capitalize %></p>
    </div>
      <% if item.status == "Inactive" %>
      <p> Item Retired</p>
      <% else %>
      <div class="cart_button">
        <%= button_to "Add to Cart", carts_path(item_id: item.id), class: "btn btn-danger" %>
      </div>
      <% end %>
    </div>
    <% end %>
</div>
<div class="back-items">
  <% @categories.each do |category| %>
    <%= link_to "#{category.title} Items", category_path(category.title) %>
    <% end %>
</div>

app/views/items/show.html.erb
<section class="center">
  <div class="items">
    <h1><%= @item.title %></h1>
    <p>Description: <%= @item.description %></p>
    <p>Price:<%= @item.price %></p>
  <div class="item_image">
    <img src="<%= asset_path(@item.image)%>"/>
  </div>
    <% if @item.status == "Inactive" %>
      <p> Item Retired</p>
    <% else %>
      <div class="cart_button">
        <%= button_to "Add to Cart", carts_path(item_id: @item.id), class: "btn btn-danger" %>
      </div>
  </div>
    <% end %>
</section>

<div class="back-items">
  <%= link_to "All Items", items_path%>
</div>