config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  get '/cart', to: "carts#show"
  delete '/carts', to: "carts#destroy"
  post '/cart/add_item', to: "carts#add_item"
  post '/cart/subtract_item', to: "carts#subtract_item"

  resources :users, only:[:new, :create, :show, :edit, :update] do
    resources :orders, only: [:create, :show, :index]
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:create, :show, :update]

  get '/:category',  to: 'categories#show', param: :slug, as: "category"

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
    get "/dashboard", to: "users#show"
    delete "/dashboard", to: "users#destroy"
    post "/dashboard", to: "users#update"
    get '/analytics-dashboard', to: "analytics#show"
    post '/analytics-dashboard', to: "analytics#update"
    patch '/items', to: "items#retire"
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :username, :password
  validates_uniqueness_of :username
  has_secure_password

  enum role: ["default", "admin"]

  has_many :orders

  def self.most_orders_placed
    user = joins(:orders).group(:user_id).order('count_id DESC').count('id').first.first
    User.find(user).username
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def show
     if params[:type] == "ordered"
      @orders = Order.ordered
     elsif params[:type] == "paid"
      @orders = Order.paid
     elsif params[:type] == "cancelled"
      @orders = Order.cancelled
     elsif params[:type] == "completed"
      @orders = Order.completed
     else
      @orders = Order.all
     end
  end

  def destroy
    order = Order.find(params[:order_id])
    order.cancelled!
    redirect_to admin_dashboard_path
  end

  def edit

  end

  def update
    if params[:update_type] == "complete"
      order = Order.find(params[:order_id])
      order.update_status_complete
      redirect_to admin_dashboard_path
    elsif params[:update_type] == "paid"
      order = Order.find(params[:order_id])
      order.update_status_paid
      redirect_to admin_dashboard_path
    else
      current_user.update(user_params)
      redirect_to admin_dashboard_path
    end
  end


  private

    def user_params
      params.require(:user).permit(:username, :password, :fullname, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_current_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      unless current_user.admin?
        redirect_to dashboard_path
      else
        redirect_to admin_dashboard_path
      end
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])

    @user.update(user_params)

    redirect_to dashboard_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :fullname, :address, :state)
  end


end

app/views/admin/users/edit.html.erb
<%= form_for [:admin, current_user] do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :fullname %>
  <%= f.text_field :fullname %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.submit "Submit" %>
<% end %>

app/views/admin/users/show.html.erb
<section class="center">
<h1>Admin Dashboard</h1>

<div class="admin-details">
  <p>Full Name: <%= current_user.fullname %></p>
  <p>Address: <%= current_user.address %></p>
</div>

<div class="back-items">
  <%= link_to "Analytics Dashboard", admin_analytics_dashboard_path %>
  <%= link_to "Add New Item", new_admin_item_path %>
  <%= link_to "View All Items", admin_items_path %>
  <%= link_to "Edit Account Details", edit_admin_user_path(current_user)  %>
</div>
</section>

<h2>Orders: </h2>
<div class="orders">
      <% @orders.each do |order| %>
    <div class="elements">
        <%if order.status == "ordered" %>
        <div class="ordered">
          User: <%=order.user.username %><br><br>
          Status: <%= order.status %><br><br>
          <%= link_to "View Order: #{order.id}", user_order_path(id: order.id, user_id: order.user.id) %><br><br>
          <%= button_to 'cancel', admin_dashboard_path(:order_id => "#{order.id}"), method: :delete %><br><br>
          <%= button_to 'mark as paid', admin_dashboard_path(:update_type => "paid", :order_id => "#{order.id}"), method: :post %><br><br>
        </div>
        <% elsif order.status == "paid" %>
        <div class = "paid">
          User: <%=order.user.username %><br>
          Status: <%= order.status %><br><br>
          <%= link_to "View Order: #{order.id}", user_order_path(id: order.id, user_id: order.user.id) %><br><br>
          <%= button_to 'cancel', admin_dashboard_path(:order_id => "#{order.id}"), method: :delete %><br><br>
          <%= button_to 'mark as completed', admin_dashboard_path(:update_type => "complete", :order_id => "#{order.id}"), method: :post %><br><br>
          </div>
        <% else %>
        <div class="other">
          User: <%=order.user.username %><br><br>
          Status: <%= order.status %><br><br>
          <%= link_to "View Order: #{order.id}", user_order_path(id: order.id, user_id: order.user.id) %><br><br><br>
        </div>
       <% end %>
    </div>
      <%end %>
  </div>
  <section class="center">
<div class="totals">
  <h3>Totals: </h3>
  <table>
   <%= link_to 'Ordered', admin_dashboard_path(:type => "ordered"), method: :get %> : <%= Order.ordered_count %> <br><br><br>
   <%= link_to 'Paid', admin_dashboard_path(:type => "paid"), method: :get %> : <%= Order.paid_count %> <br><br><br>
    <%= link_to 'Cancelled', admin_dashboard_path(:type => "cancelled"), method: :get %> : <%= Order.cancelled_count %> <br><br><br>
    <%= link_to 'Completed', admin_dashboard_path(:type => "completed"), method: :get %> : <%= Order.completed_count %> <br><br><br>
    <%= link_to 'All', admin_dashboard_path %> : <%= Order.all.count %><br><br><br>
  </table>
</div>
</section>