config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/dashboard", to: "users#show"
  get '/cart', to: "carts#show"
  delete '/carts', to: "carts#destroy"
  post '/cart/add_item', to: "carts#add_item"
  post '/cart/subtract_item', to: "carts#subtract_item"

  resources :users, only:[:new, :create, :show, :edit, :update] do
    resources :orders, only: [:create, :show, :index]
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:create, :show, :update]

  get '/:category',  to: 'categories#show', param: :slug, as: "category"

  namespace :admin do
    resources :users, only: [:show, :edit, :update]
    get "/dashboard", to: "users#show"
    delete "/dashboard", to: "users#destroy"
    post "/dashboard", to: "users#update"
    get '/analytics-dashboard', to: "analytics#show"
    post '/analytics-dashboard', to: "analytics#update"
    patch '/items', to: "items#retire"
    resources :items, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user && !current_user.admin? %>
    <nav class="container">
        <h1> Logged in as <%= current_user.username%>!</h1>
        <div class='log'>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Shop', items_path %>
          <%= link_to 'View Cart', cart_path %>
          <%= link_to 'Log Out', logout_path, :method => :delete %>
        </div>
      </nav>
      <% elsif current_user && current_user.admin? %>
      <nav class="container">
        <h1> Logged in as <%= current_user.username%>!</h1>
        <div class='log'>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Shop', items_path %>
          <%= link_to 'View Cart', cart_path %>
          <%= link_to 'Dashboard', admin_dashboard_path %>
          <%= link_to 'Analytics Dashboard', admin_analytics_dashboard_path %>
          <%= link_to 'Log Out', logout_path, :method => :delete %>
         </div>
      </nav>
    <% else %>
      <nav class="container">
        <h1>Welcome to the Keen Bean!</h1>
        <div class='log'>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Shop', items_path %>
          <%= link_to 'View Cart', cart_path %>
          <%= link_to "Login", login_path%>
      <% end %>
        </div>
      </nav>
      <p class="cart">Cart: <%= @cart.total_count %></p>
      <% flash.each do |type, message| %>
        <%= content_tag :div, message.html_safe, class: type  %>
      <% end %>
    <%= yield %>
  </body>
</html>